---

- name: Creating "docker" system group
  group:
    name: docker
    state: present


- name: Adding current user to "docker" group
  user:
    name: '{{ lookup("env", "USER") }}'
    groups: docker


- name: Starting/enabling docker service
  systemd:
    name: docker
    state: started
    enabled: yes


- name: Adding current user to sudoers
  lineinfile:
    path: '/etc/sudoers.d/workstation'
    line: '{{ lookup("env", "USER") }} ALL=(ALL) ALL'
    create: yes