---

- name: Updating Homebrew and upgrading all packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes


- name: Including external repository for fonts
  homebrew_tap:
    name: homebrew/cask-fonts


- name: Installing KeePassXC
  homebrew_cask:
    name: keepassxc
    state: present


- name: Installing Firefox
  homebrew_cask:
    name: firefox
    state: present


- name: Installing Hack Nerd Font
  homebrew_cask:
    name: font-hack-nerd-font
    state: present


- name: Installing Emacs
  homebrew_cask:
    name: emacs
    state: present


- name: Installing Docker tools
  homebrew_cask:
    name: docker
    state: present


- name: Installing Neovim
  homebrew:
    name: neovim
    state: present


- name: Installing command line applications
  homebrew:
    name: '{{ hb_cli }}'
    state: present


- name: Installing shell, terminal multiplexer etc
  homebrew:
    name: '{{ hb_sys }}'
    state: present


- name: Installing devops/automation tools
  homebrew:
    name: '{{ hb_devops }}'
    state: present


- name: Installing multimedia programs & codecs
  homebrew:
    name: '{{ hb_media }}'
    state: latest


- name: Installing development toolchains
  homebrew:
    name: '{{ hb_dev }}'
    state: present
