---

- name: Updating Homebrew and upgrading all packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes


- name: Including external repository for fonts
  homebrew_tap:
    name: homebrew/cask-fonts


- name: Including personal repository of formulas
  homebrew_tap:
    name: caian-org/homebrew-cai


- name: Installing VirtualBox
  homebrew_cask:
    name: virtualbox
    state: present


- name: Installing Transmission
  homebrew_cask:
    name: transmission
    state: present


- name: Installing Chromium
  homebrew_cask:
    name: chromium
    state: present


- name: Installing Hack Nerd Font
  homebrew_cask:
    name: font-hack-nerd-font
    state: present


- name: Installing Docker tools
  homebrew_cask:
    name: docker
    state: present


- name: Installing Neovim
  homebrew:
    name: neovim
    state: present


- name: Installing command line applications
  homebrew:
    name: '{{ hb_cli }}'
    state: present


- name: Installing devops/automation tools
  homebrew:
    name: '{{ hb_devops }}'
    state: present


- name: Installing multimedia programs & codecs
  homebrew:
    name: '{{ hb_media }}'
    state: latest


- name: Installing development toolchains
  homebrew:
    name: '{{ hb_dev }}'
    state: present
