---

- name: Updating Homebrew and upgrading all packages
  homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Including external repository/tap for fonts
  homebrew_tap:
    name: homebrew/cask-fonts

- name: Installing casks
  homebrew_cask:
    name: '{{ hb_cask }}'
    state: installed
  ignore_errors: true

- name: Installing CLI utilities
  homebrew:
    name: '{{ hb_cli_utilities }}'
    state: installed
  ignore_errors: true

- name: Installing devops/automation tools
  homebrew:
    name: '{{ hb_devops }}'
    state: installed
  ignore_errors: true

- name: Installing multimedia programs & codecs
  homebrew:
    name: '{{ hb_media }}'
    state: installed
  ignore_errors: true

- name: Installing development toolchains
  homebrew:
    name: '{{ hb_dev }}'
    state: installed
  ignore_errors: true
