---

- name: Updating Homebrew and upgrading all packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes


- name: Including external repository for fonts
  homebrew_tap:
    name: homebrew/cask-fonts


- name: Including personal repository of formulas
  homebrew_tap:
    name: caian-org/homebrew-cai


- name: Installing casks
  homebrew_cask:
    name: '{{ hb_cask }}'
    state: latest


- name: Installing command line applications
  homebrew:
    name: '{{ hb_cli }}'
    state: latest
  ignore_errors: yes


- name: Installing devops/automation tools
  homebrew:
    name: '{{ hb_devops }}'
    state: latest


- name: Installing multimedia programs & codecs
  homebrew:
    name: '{{ hb_media }}'
    state: latest


- name: Installing development toolchains
  homebrew:
    name: '{{ hb_dev }}'
    state: latest
