---

hb_cli:
  - bat
  - btop
  - exa
  - fd
  - fdupes
  - figlet
  - gnupg
  - gpg
  - htop
  - httpie
  - itchyny/tap/mmv
  - jq
  - neofetch
  - p7zip
  - pv
  - pwgen
  - rar
  - rclone
  - renameutils
  - rsync
  - stow
  - tree
  - unrar
  - unzip
  - upx
  - wget
  - xz
  - zip
  - zsh
  - neovim

  # comes from tap caian-org/homebrew-formulas
  - tmux31c


hb_devops:
  - awscli
  - docker-compose


hb_media:
  - asciinema
  - ffmpeg
  - flac
  - imagemagick
  - lame


hb_dev:
  - dotnet-sdk
  - elixir
  - erlang
  - git
  - git-filter-repo
  - go
  - gradle
  - lua
  - luajit
  - ngrok
  - nim
  - node
  - nvm
  - openjdk
  - pipenv
  - pyenv
  - python
  - ruby
  - rustup
  - shellcheck
  - pnpm


hb_cask:
  - chromium
  - docker
  - eqmac
  - font-hack-nerd-font
  - qbittorrent
  - virtualbox
  - vlc
