---

hb_cli:
  - jq
  - xz
  - fd
  - upx
  - bat
  - exa
  - mas
  - fzf
  - nnn
  - zip
  - unzip
  - rar
  - unrar
  - p7zip
  - tree
  - stow
  - htop
  - pwgen
  - neofetch
  - entr
  - renameutils
  - figlet
  - itchyny/tap/mmv
  - wget
  - httpie
  - zsh
  - gpg
  - gnupg
  - rclone
  - rsync
  # comes from tap caian-org/homebrew-formulas
  - sshpass
  - steghide
  - tmux31c


hb_devops:
  - awscli
  # - ansible
  - docker-compose


hb_media:
  - mpc
  - mpd
  - mpv
  - asciinema
  - youtube-dl
  - ffmpeg
  - flac
  - lame


hb_dev:
  - git
  - ctags
  - shellcheck
  - lcov
  # python
  - python
  - pipenv
  - pyenv
  # C/C++
  - ninja
  - llvm
  - autoconf
  - automake
  - ccls
  - gdb
  - cmake
  - conan
  # Java/JVM
  - gradle
  - openjdk
  - kotlin
  # js
  - node
  - nvm
  # (misc) interpreted
  - lua
  - ruby
  # (misc) compiled
  - go
  - erlang
  - elixir
  - vlang
  - dotnet-sdk
  - rust
  - crystal
