---

- name: Clonning dotfiles
  git:
    repo: '{{ dots_repo_url }}'
    dest: '{{ home_dir_path }}/dots'
    force: yes


- name: Stowing packages
  stow:
    package: '{{ manjaro_stow_pkgs }}'
    state: supress
    dir: '{{ home_dir_path }}/dots/pkgs'
  when: ev_os == 'manjaro'


- name: Stowing packages
  stow:
    package: '{{ macos_stow_pkgs }}'
    state: supress
    dir: '{{ home_dir_path }}/dots/pkgs'
  when: ev_os == 'macos'
