---

pkg_aur_misc:
  - libxlsxwriter
  - nerd-fonts-terminus
  - farbfeld


pkg_aur_cli:
  - python-pywal
  - cava
  - ls_extended
  - sc-im
  - megacmd-bin


pkg_aur_gui:
  - tor-browser
  - visual-studio-code-bin
  - popcorntime-bin
  - google-chrome
