---

- name: Linking bin directory
  file:
    src: '{{ bin_source_path }}'
    dest: '{{ bin_dest_path }}'
    state: link
    force: true

- name: Installing NodeJS packages
  make:
    chdir: '{{ bin_dest_path }}/njs'

- name: Installing Python packages
  make:
    chdir: '{{ bin_dest_path }}/pip'
