name: lint-docker

# only when something on "docker" dir has changed
on:
  push:
    paths:
      - 'bin/docker/**'

jobs:
  lint-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: caian
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run script
        run: |
          cd bin/docker
          ./lint-all.sh
